### ISSUE TITLE
Infinite loop entering task names in post hook when running python 2.7

### ISSUE THREAD

**Issue by huguesv** [iknite/cookiecutter-ansible-role#5]
Found it by accident. I figured you'd like to know :)

**Comment by iknite** [comment]
It run until an empty name is given.
That way you can give N task names (or handlers, or ...)
It's explained in Usage section of the readme, but maybe it's not clear enough. 

I'm closing this, If there is something I misunderstood please let me know

**Comment by huguesv** [comment]
Sorry if I wasn't clear.  That works fine on Python 3.5, but not on Python 2.7.  That's due to the use of `input()`, which needs to be `raw_input()` when running on 2.7.

**Comment by iknite** [comment]
Hi again! 

I'd tested both environments and it's working fine here, both 2.7.11 & 3.5.1. 
Care to give more details about the loop? 

I'm guessing it's more about the two levels prompt, because the first one level (it ends in `[yes]`) ask for a creation/removal of the folder and the second one it's about the content of the files.

Cheers :beers:
